src/NorthWind2/Controllers/CartController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using NorthWind2.Models;
using NorthWind2.Repositories;
using NorthWind2.Services;
using NorthWindCoreData;
using NorthWindCoreData.Models;

namespace NorthWind2.Controllers
{
    public class CartController : Controller
    {
        private readonly ICustomerRepository _customerRepository;
       


        public CartController(ICustomerRepository customerRepository)
        {
            _customerRepository = customerRepository;
        
           
        }

        // GET: ShoppingCart
        public ActionResult Index()
        {
            
            //if (HttpContext.User.Identity.IsAuthenticated)
            //{
            //    var cart = GetCartFromCookie();
            //    Customer customer = GetAutenticatedCustomer();
            //    _customerRepository.SyncShoppingCart(customer.Email, GetCartFromCookie());
            //}

            return View();
        }

        [HttpPost]
        [Authorize]
        public ActionResult Save(List<CartViewModel> cartView)
        {
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                var customer = GetAutenticatedCustomer();
                _customerRepository.SyncShoppingCart(customer.Email, cartView);
            }
            return View("Index");
        }

        public ActionResult ThankYou()
        {

            return View();
        }
        //private List<CartViewModel> GetCartFromCookie()
        //{
        //    var cookie = HttpContext.Request.Cookies.Get("cart");
        //    var result = cookie == null ? new List<CartViewModel>() : DTDCookieToViewModel(cookie);
        //    return result;

        //}

        private List<CartViewModel> DtdCookieToViewModel(HttpCookie cookie)
        {
            var cookieValue = HttpUtility.UrlDecode(cookie.Value);
            var cartViewModels = JsonConvert.DeserializeObject<List<CartViewModel>>(cookieValue);
            
            return cartViewModels;
        }

        private Customer GetAutenticatedCustomer()
        {

            return User.Identity.IsAuthenticated ? GetCustomerByEmail() : new Customer();

        }

        private Customer GetCustomerByEmail()
        {
            var user = HttpContext.User.Identity.Name;
            var customers = _customerRepository.GetAll();
            return customers.First(x => x.Email == user);
        }

        
    }
}

src/NorthWind2/Controllers/CategoryController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using NorthWind2.Repositories;
using NorthWindCoreData.Models;

namespace NorthWind2.Controllers
{
    public class CategoryController : Controller
    {
        private readonly CategoryRepository _repository;

        public CategoryController(CategoryRepository repository)
        {
            _repository = repository;
        }

        // GET: Category
        public ActionResult Index()
        {
            // var context = new ApplicationContext("NorthwindContext");
            var categories = _repository.GetAll();
            return View(categories);
        }

        public ActionResult Products(int categoryId)
        {
            //// var context = new ApplicationContext("NorthwindContext");
            // var categories = new Repository<Category>(context).GetAll().ToList();
            // var category = categories.Single(x => x.CategoryID == categoryId);
            // var products= categories.Single(x => x.CategoryID== categoryId).Products.ToList();
            //// products.ForEach(x => x.ProductName =HttpUtility.JavaScriptStringEncode(x.ProductName));

            //var categories = _repository.GetAll();
            //var category = categories.SingleOrDefault(x => x.CategoryID == categoryId);
            var category = _repository.Find(x => x.CategoryID == categoryId).SingleOrDefault();
            var products = category != null ? category.Products.ToList() : new List<Product>();

            return View("Products", products);
        }
    }
}

src/NorthWind2/Controllers/ProductsController.cs
using System.Linq;
using System.Web.Mvc;
using NorthWind2.Repositories;
using NorthWindCoreData;
using NorthWindCoreData.Models;

namespace NorthWind2.Controllers
{
    public class ProductController : Controller
    {
        IRepository<Product> _product;
        private readonly CategoryRepository _categoryRepository;
        private readonly IRepository<Product> _productRepository;

        public ProductController(IUnitOfWork unitOfWork,CategoryRepository categoryRepository)
        {

            _product = unitOfWork.Product;
            _categoryRepository = categoryRepository;
            //_productRepository = productRepository;
        }

        // GET: Product
        public ActionResult Index()
        {

           var test_one_db = _categoryRepository.GetAll().ToList();
            var products = _product.GetAll().ToList();
           
            return View(products);
        }

        public ActionResult ReadAllProducts()
        {
            return Content("This is atest");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            // var product = _product.GetAll().ToList().SingleOrDefault(x => x.ProductID == id);

            var product = _product.Find(x => x.ProductID == id).Single();

            return View("EditProduct", product);
        }

        [HttpPost]
        public ActionResult Edit(Product product)
        {
            _product.Update(product);
           // _product.Save();
            return View("EditProduct", product);

        }
    }
}

src/NorthWind2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html data-ng-app="registrationModule">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/cssbundles")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/angular.min.js"></script>
    <script src="~/Scripts/angular-route.min.js"></script>
    <script src="~/Scripts/ngNotificationsBar.min.js"></script>
    <script src="~/Scripts/angular-ui/ui-bootstrap.min.js"></script>
    <script src="~/Scripts/angular-ui/ui-bootstrap-tpls.min.js"></script>

    <script src="~/Scripts/angularApp/app.js"></script>
    <script src="~/Scripts/factories/cartrepository.js"></script>
    <script src="~/Scripts/angularController/cartController.js"></script>
    <script src="~/Scripts/factories/userservice.js"></script>
</head>
<body ng-controller="cartController">
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar">testst</span>
                    <span class="icon-bar">dddddddddddddddddd</span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <notifications-bar class="notifications"></notifications-bar>
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Northwind", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })</li>
                    <li>@Html.ActionLink("Products", "Index", "Product", new { area = "" }, new { @class = "navbar-brand" })</li>
                    <li>@Html.ActionLink("Categories", "Index", "Category", new { area = "" }, new { @class = "navbar-brand" })</li>
                    <li>

                    </li>
                </ul>
                <a href="@Url.Action("index", "Cart")" id="lastVal"><img src="~/images/glyphicons-203-shopping-cart.png" class="img-thumbnail bg-info" />({{lastVal}})</a>

                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>

    <div class="container">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
 
    @RenderSection("Angularscripts", required: false)
    @RenderSection("Scripts", required: false)
</body>
</html>